/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JDialog;

import Base_de_Datos.conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thomy
 */
public class Movimientos_usuarios extends javax.swing.JDialog {

    /**
     * Creates new form Movimientos_usuarios
     */
    
    
    conexion obj = new conexion();
    String sql;
    
    public Movimientos_usuarios(java.awt.Frame parent, boolean modal){
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        DatosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Movimientos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 237, 240));

        jScrollPane1.setViewportView(jTable_Movimientos);
        if (jTable_Movimientos.getColumnModel().getColumnCount() > 0) {
            jTable_Movimientos.getColumnModel().getColumn(0).setHeaderValue("Placa");
            jTable_Movimientos.getColumnModel().getColumn(1).setHeaderValue("Tipo Vehiculo");
            jTable_Movimientos.getColumnModel().getColumn(2).setHeaderValue("Hora Entrada");
            jTable_Movimientos.getColumnModel().getColumn(3).setHeaderValue("Hora Salida");
            jTable_Movimientos.getColumnModel().getColumn(4).setHeaderValue("Pagado");
            jTable_Movimientos.getColumnModel().getColumn(5).setHeaderValue("Usuario Entrada");
            jTable_Movimientos.getColumnModel().getColumn(6).setHeaderValue("Usuario Salida");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //METODO PARA RELLENAR LA TABLA
    private void DatosTabla(){
        
        DefaultTableModel modelo = new DefaultTableModel(new String [] {
        "Placa", "Tipo Vehiculo", "Hora Entrada", "Hora Salida", "Pagado", "Usuario Entrada", "Usuario Salida"
    },0);
        
        
        try {
            
            sql = "SELECT e.placa_vehiculo,e.tipo_vehiculo,e.horaentrada_vehiculo,e.horasalida_vehiculo,e.valorpagado,CONCAT (v.nombre_empleado,' ', v.apellido_empleado),e.usuario_salida" +
                    " FROM vehiculos AS e INNER JOIN usuarios AS u ON e.usuario = u.usuario INNER JOIN empleados AS v ON v.id_empleado = u.id_empleado";
            
            ResultSet datos = obj.ejecutarSQLSelect2(sql);
            
            while (datos.next()) {
                
                String horasalida = datos.getString(4);
                String horaentrada = datos.getString(3);
                String pago = datos.getString(5);
                
                
                if (horasalida == null) {
                    
                    horasalida = "No ha salido";
                    pago = "0";
                    
                } else {
                    
                    horaentrada = datos.getString(3).substring(0, 16);
                    horasalida = datos.getString(4).substring(0,16);
                    pago = datos.getString(5);
                    
                }
                
                Object[] fila = {datos.getString(1),
                   datos.getString(2),
                   horaentrada,
                   horasalida,
                   "$" + pago,
                   datos.getString(6),
                   datos.getString(7),
                   };
 
                modelo.addRow(fila);
            }
            
            jTable_Movimientos.setModel(modelo);
                    
        } catch (SQLException ex) {
            
            System.out.println(ex);
            Logger.getLogger(Movimientos_usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movimientos_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movimientos_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movimientos_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movimientos_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Movimientos_usuarios dialog = new Movimientos_usuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Movimientos;
    // End of variables declaration//GEN-END:variables
}
