/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JDialog;

import Base_de_Datos.conexion;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author thomy
 */
public class ver_usuarios extends javax.swing.JDialog {

    /**
     * Creates new form ver_usuarios
     */
    
   // DefaultTableModel modelo;
    String sql;
    conexion objcon = new conexion();
    registrar_usuario ru = new registrar_usuario(null, rootPaneCheckingEnabled);
    MyDefaultTableModel2 mdtm = new MyDefaultTableModel2();
    JTable jtable = new JTable();
    
    public ver_usuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        jtable.setModel(mdtm);
        mdtm.setTable(jTable_empleados);
        
        
        mdtm.setOnGuardarDatosListener(datos -> {
            Arrays.stream(datos).iterator().forEachRemaining(o -> {
                System.out.println(o.toString());
            });
        });
        
        crearTabla();
        rellenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupM_tablaEmp = new javax.swing.JPopupMenu();
        jMenuItem_ver = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_editar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_suspender = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_empleados = new javax.swing.JTable();
        jButton_nuevoE = new javax.swing.JButton();

        jMenuItem_ver.setText("Ver usuario");
        jMenuItem_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_verActionPerformed(evt);
            }
        });
        jPopupM_tablaEmp.add(jMenuItem_ver);
        jPopupM_tablaEmp.add(jSeparator1);

        jMenuItem_editar.setText("Editar");
        jMenuItem_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_editarActionPerformed(evt);
            }
        });
        jPopupM_tablaEmp.add(jMenuItem_editar);
        jPopupM_tablaEmp.add(jSeparator2);

        jMenuItem_suspender.setText("Activar/Suspender");
        jPopupM_tablaEmp.add(jMenuItem_suspender);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable_empleados.setModel(mdtm);
        jTable_empleados.setComponentPopupMenu(jPopupM_tablaEmp);
        jScrollPane1.setViewportView(jTable_empleados);

        jButton_nuevoE.setText("Nuevo Empleado");
        jButton_nuevoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevoEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton_nuevoE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton_nuevoE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_nuevoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevoEActionPerformed
        // TODO add your handling code here:
        ru.setVisible(true);
    }//GEN-LAST:event_jButton_nuevoEActionPerformed

    private void jMenuItem_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_verActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_verActionPerformed

    private void jMenuItem_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_editarActionPerformed

    }//GEN-LAST:event_jMenuItem_editarActionPerformed

    //METODO PARA CREAR LA TABLA
    public final void crearTabla(){
        
        TableColumnModel columnModel = jTable_empleados.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(80);
        columnModel.getColumn(1).setPreferredWidth(70);
        columnModel.getColumn(2).setPreferredWidth(140);
        columnModel.getColumn(3).setPreferredWidth(80);
        columnModel.getColumn(4).setPreferredWidth(70);
        columnModel.getColumn(5).setPreferredWidth(50);
        columnModel.getColumn(6).setPreferredWidth(30);
        columnModel.getColumn(7).setPreferredWidth(30);
        
        //mdtm = (MyDefaultTableModel2) jTable_empleados.getModel();
        //mdtm.setRowCount(0);
        
    } //Fin Crear Tabla
    
    //METODO PARA RELLENAR LA TABLA
    public final void rellenarTabla(){
        try{
            
            sql = "SELECT CONCAT(e.nombre_empleado,' ',e.apellido_empleado) AS Nombre,e.cedula_empleado,e.correo_empleado,e.telefono_empleado,u.Posicion, u.Estado FROM empleados AS e INNER JOIN usuarios AS u on e.id_empleado = u.id_empleado ";
            objcon.ejecutarSQLSelect(sql);

            conexion.resultado.first();

            do {

                Object[] fila = {conexion.resultado.getString(1),
                                 conexion.resultado.getString(2),
                                 conexion.resultado.getString(3), 
                                 conexion.resultado.getString(4),
                                 conexion.resultado.getString(5),
                                 conexion.resultado.getString(6),
                                 "Editar",
                                 false};
                
                mdtm.addRow(fila);
                
            } while (conexion.resultado.next());
            
        } catch (SQLException ex) {
             Logger.getLogger(ver_usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//Fin rellenar Tabla
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ver_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ver_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ver_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ver_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ver_usuarios dialog = new ver_usuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_nuevoE;
    private javax.swing.JMenuItem jMenuItem_editar;
    private javax.swing.JMenuItem jMenuItem_suspender;
    private javax.swing.JMenuItem jMenuItem_ver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupM_tablaEmp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable_empleados;
    // End of variables declaration//GEN-END:variables
}
